### ISSUE TITLE
some error

### ISSUE THREAD

**Issue by tongchangD** [hpc203/yolov5-6.1-opencv-onnxrun#12]
现在yolov5导出来的模型都将三个检测框的结果合并到一个维度里面去了，为1x25200x38,不再是单独的了，代码可能得改改了

**Comment by chengdashia** [comment]
> 现在yolov5导出来的模型都将三个检测框的结果合并到一个维度里面去了，为1x25200x38,不再是单独的了，代码可能得改改了

大佬，怎么改啊？

**Comment by tongchangD** [comment]
@chengdashia  你要改什么

**Comment by tongchangD** [comment]
@chengdashia  对不起，刚刚睡醒有点小懵，你给我个小邮箱，我将代码发你

**Comment by chengdashia** [comment]
> @chengdashia 对不起，刚刚睡醒有点小懵，你给我个小邮箱，我将代码发你

大佬好，我按照仓库的给的那个知乎的网址，将export和yolo文件里面的代码进行修改后，可以使用仓库里面的python代码对模型进行推理。但是在使用c++的那个代码的时候，onnxruntime有问题。不知道您有没有遇到。使用OpenCV的dnn部署是没有问题的。我的邮箱是17337995232@163.com

**Comment by chengdashia** [comment]
> @chengdashia 对不起，刚刚睡醒有点小懵，你给我个小邮箱，我将代码发你

不知道大佬使用的onnxruntime是哪个版本啊？

**Comment by chengdashia** [comment]
> @chengdashia 对不起，刚刚睡醒有点小懵，你给我个小邮箱，我将代码发你

?

**Comment by tongchangD** [comment]
已发

**Comment by chengdashia** [comment]
> 已发

没收到啊？
