### ISSUE TITLE
win10 cpp opencv 推理无法运行

### ISSUE THREAD

**Issue by fire717** [hpc203/yolov5-6.1-opencv-onnxrun#4]
环境：win10、VS2019、OpenCV4.5.4
使用提供的模型yolov5n.onnx，运行opencv下的main.cpp

报错Expression：vector subscript out of range

debug模型加载、forword都没问题。

初步判断是在detect的这两行报错，应该是网络输出结果有问题？	
```
int num_proposal = outs[0].size[1];
int nout = outs[0].size[2];
```

我打印outs				
`cout << "outs size " << outs.size() << " " << outs[0].cols << " " << outs[0].rows << endl;`

得到的结果是1 -1 -1 不知道是否正常？

**Comment by fire717** [comment]
另外python版本是可以跑通的

**Comment by fire717** [comment]
onnxruntime也是，py能运行，cpp的就报错：
`严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK2019	无法解析的外部符号 OrtGetApiBase，函数 "void __cdecl `dynamic initializer for 'public: static struct OrtApi const * const Ort::Global<void>::api_''(void)" (??__E?api_@?$Global@X@Ort@@2PEBUOrtApi@@EB@@YAXXZ) 中引用了该符号	opencvdnn	E:\Workshop\CPP\opencvdnn\opencvdnn\opencvdnn\main.obj	1	
`
onnxruntime版本win x64 1.6.0

**Comment by hpc203** [comment]
> 环境：win10、VS2019、OpenCV4.5.4 使用提供的模型yolov5n.onnx，运行opencv下的main.cpp
> 
> 报错Expression：vector subscript out of range
> 
> debug模型加载、forword都没问题。
> 
> 初步判断是在detect的这两行报错，应该是网络输出结果有问题？
> 
> ```
> int num_proposal = outs[0].size[1];
> int nout = outs[0].size[2];
> ```
> 
> 我打印outs `cout << "outs size " << outs.size() << " " << outs[0].cols << " " << outs[0].rows << endl;`
> 
> 得到的结果是1 -1 -1 不知道是否正常？

不能这么打印的，为什么会出现-1，请看这篇文章里的原因分析
https://blog.csdn.net/nihate/article/details/113849665

**Comment by fire717** [comment]
OK
