### ISSUE TITLE
main.cpp 进行推理闪退

### ISSUE THREAD

**Issue by caihaocong** [hpc203/yolov5-6.1-opencv-onnxrun#7]
您好，我用qt5.7.1 和 opencv4.5.3 使用您的 main.cpp 进行推理，加载是您百度的模型权重，程序直接闪退。请问您知道是什么原因吗？

**Comment by caihaocong** [comment]
找到原因了。没有把 class.names 移过去

**Comment by hpc203** [comment]
升级opencv版本试一下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月12日(周五) 下午4:49
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [hpc203/yolov5-v6.1-opencv-onnxrun] main.cpp 进行推理闪退 (Issue #7)




 
您好，我用qt5.7.1 和 opencv4.5.3 使用您的 main.cpp 进行推理，加载是您百度的模型权重，程序直接闪退。请问您知道是什么原因吗？
